// import { ParkingSlot } from "./parking-slots-module"; 

// export const parkingSlots: ParkingSlot[] = [
//     { id: 'A1', vehicleType: '2W', availability: 'available', status: 'available' },
//     { id: 'A2', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//     { id: 'A3', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'A4', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'A5', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'A6', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'A7', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'A8', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'A9', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'A10', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'B1', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'B2', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'B3', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'B4', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'B5', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'B6', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'B7', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'B8', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'B9', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'B10', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'C1', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'C2', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'C3', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'C4', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'C5', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'C6', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'C7', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'C8', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'C9', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'C10', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'D1', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'D2', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'D3', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'D4', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'D5', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'D6', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'D7', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'D8', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
//   { id: 'D9', vehicleType: '2W', availability: 'available', status: 'available' },
//   { id: 'D10', vehicleType: '4W', availability: 'occupied', status: 'occupied' },
// ];
